Repository stripe/stripe-ios, pull requests merged in 2024-09, with the labels that each got.

#3990 Make dictionary extension methods SPI-public
  StripeCore/StripeCore/Source/Categories/Dictionary+Stripe.swift
Labels: modifies public API

#3991 Add Appearance APIs for primary button customization in disabled state + snapshot tests + playground update
  CHANGELOG.md
  Example/PaymentSheet Example/PaymentSheet Example/AppearancePlaygroundView.swift
  Stripe/StripeiOSTests/ConfirmButtonSnapshotTests.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheetAppearance.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Views/ConfirmButton.swift
  Tests/ReferenceImages_64/StripeiOS_Tests.ConfirmButtonSnapshotTests/testConfirmButtonDefaultDisabledColor@3x.png
  Tests/ReferenceImages_64/StripeiOS_Tests.ConfirmButtonSnapshotTests/testConfirmButtonDisabledColor@3x.png
  Tests/ReferenceImages_64/StripeiOS_Tests.ConfirmButtonSnapshotTests/testConfirmButtonDisabledColorWhenSetBackgroundColorAndNoSetDisabledColor@3x.png
  Tests/ReferenceImages_64/StripeiOS_Tests.ConfirmButtonSnapshotTests/testConfirmButtonDisabledColorWhenSetDisabledBackgroundAndPrimaryColors@3x.png
  Tests/ReferenceImages_64/StripeiOS_Tests.ConfirmButtonSnapshotTests/testConfirmButtonDisabledColorWhenSetPrimaryColorAndNoSetBackgroundColorOrDisabledColor@3x.png
Labels: modifies public API

#4000 Remove early access for CVC Recollection
  CHANGELOG.md
  Example/PaymentSheet Example/PaymentSheet Example/PlaygroundController.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheetIntentConfiguration.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/PaymentSheetFlowControllerViewControllerSnapshotTests.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/PaymentSheetSnapshotTests.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/PaymentSheetVerticalViewControllerSnapshotTest.swift
Labels: don't merge, modifies public API

#4062 Update embedded appearance API and add to playground
  Example/PaymentSheet Example/PaymentSheet Example/AppearancePlaygroundView.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Embedded/EmbeddedPaymentMethodsView.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Embedded/RadioButton.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheetAppearance.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Vertical Main Screen/RowButton.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Views/ShadowedRoundedRectangleView.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/EmbeddedPaymentMethodsViewSnapshotTests.swift
Labels: embedded

#4067 Embedded example
  Example/PaymentSheet Example/PaymentSheet Example.xcodeproj/project.pbxproj
  Example/PaymentSheet Example/PaymentSheet Example/ExampleEmbeddedElementCheckoutViewController.swift
  Example/PaymentSheet Example/PaymentSheet Example/Resources/Base.lproj/Main.storyboard
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Embedded/EmbeddedPaymentElement.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Embedded/EmbeddedPaymentElementDelegate.swift
Labels: embedded

#4063 [BANKCON-14531] Update Instant Debits flow to call `/share` endpoint for Panther payments
  StripeCore/StripeCore/Source/Helpers/Async.swift
  StripeFinancialConnections/StripeFinancialConnections/Source/API Bindings/FinancialConnectionsAPIClient.swift
  StripeFinancialConnections/StripeFinancialConnections/Source/API Bindings/Models/FinancialConnectionsPaymentDetails.swift
  StripeFinancialConnections/StripeFinancialConnections/Source/Common/HostController.swift
  StripeFinancialConnections/StripeFinancialConnections/Source/Native/NativeFlowController.swift
  StripeFinancialConnections/StripeFinancialConnections/Source/Native/NativeFlowDataManager.swift
  StripeFinancialConnections/StripeFinancialConnectionsTests/EmptyFinancialConnectionsAPIClient.swift
Labels: skip dead code check
