Repository stripe/stripe-ios, pull requests merged in 2025-06, with the labels that each got.

#4974 Fix typo in docs
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheetAppearance.swift
Labels: embedded

#4985 Fix build on Xcode 26
  StripePaymentsUI/StripePaymentsUI/Source/UI Components/STPAUBECSDebitFormView.swift
Labels: modifies public API

#5001 Adds ShopPayConfiguration for WalletButtonsView
  Example/PaymentSheet Example/PaymentSheet Example/ExampleWalletButtonsView.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentElementConfiguration.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheetConfiguration.swift
Labels: skip dead code check

#4999 flatWithChevron row style API
  CHANGELOG.md
  Example/PaymentSheet Example/PaymentSheet Example/AppearancePlaygroundView.swift
  StripePaymentSheet/StripePaymentSheet.xcodeproj/project.pbxproj
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Embedded/EmbeddedPaymentElement+Internal.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Embedded/EmbeddedPaymentMethodsView.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheetAppearance.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/STPAnalyticsClient+PaymentSheet.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Vertical Main Screen/RightAccessoryButton.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Vertical Main Screen/RowButton.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/Vertical Main Screen/RowButtonFlatWithChevron.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/EmbeddedPaymentElementSnapshotTests.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/EmbeddedPaymentElementTest.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/EmbeddedPaymentMethodsViewSnapshotTests.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/RightAccessoryButtonTest.swift
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentElementSnapshotTests/testShowsChangeButton_flatChevronWithCompletionHandler__afterpay@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentElementSnapshotTests/testShowsChangeButton_flatChevronWithCompletionHandler__card@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentElementSnapshotTests/testShowsChangeButton_flatChevronWithCompletionHandler__us_bank_account_canceled@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentElementSnapshotTests/testShowsChangeButton_flatChevronWithCompletionHandler__us_bank_account_continue@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_borderWidth@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_color@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_cornerRadius@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_largeFont@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_noApplePay@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_noLink@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_promoBadge_selected@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_promoBadge_unselected@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_rowHeight@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_rowHeightSingleLine@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_savedPaymentMethod@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_selectedBorder@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_smallFont@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.EmbeddedPaymentMethodsViewSnapshotTests/testEmbeddedPaymentMethodsView_flatWithChevron_spacing@3x.png
Labels: modifies public API

#5005 Initial Shop Pay WKWebView bridge
  Example/PaymentSheet Example/PaymentSheet Example/ExampleWalletButtonsView.swift
  StripePaymentSheet/StripePaymentSheet.xcodeproj/project.pbxproj
  StripePaymentSheet/StripePaymentSheet/Source/Internal/ECE/ECEBridgeTypes.swift
  StripePaymentSheet/StripePaymentSheet/Source/Internal/ECE/ECEIndexHtml.swift
  StripePaymentSheet/StripePaymentSheet/Source/Internal/ECE/ECEViewController.swift
  StripePaymentSheet/StripePaymentSheet/Source/Internal/ECE/ShopPayECEPresenter.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheetConfiguration.swift
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/WalletButtonsView/WalletButtonsView.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/ECE/ECEIntegrationTests.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/ECE/ECETestHelpers.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/ECE/ECEViewControllerSnapshotTests.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/ECE/ECEViewControllerTests.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/ECE/ShopPayECEPresenterTests.swift
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_CompactWidth@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_DarkMode@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_Default@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_LargeContentSize@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_LoadingState@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_WithPopup@3x.png
Labels: skip dead code check

#5042 Reduce shopPay jank
  Example/PaymentSheet Example/PaymentSheet Example/ExampleWalletButtonsView.swift
  StripePaymentSheet/StripePaymentSheet.xcodeproj/project.pbxproj
  StripePaymentSheet/StripePaymentSheet/Source/Internal/ECE/ECEIndexHtml.swift
  StripePaymentSheet/StripePaymentSheet/Source/Internal/ECE/ECEViewController.swift
  StripePaymentSheet/StripePaymentSheet/Source/Internal/ECE/ShopPayECEPresenter.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/ECE/ECEIntegrationTests.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/ECE/ECEViewControllerSnapshotTests.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/ECE/ECEViewControllerTests.swift
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_CompactWidth@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_DarkMode@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_Default@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_LargeContentSize@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_LoadingState@3x.png
  Tests/ReferenceImages_64/StripePaymentSheetTests.ECEViewControllerSnapshotTests/testECEViewController_WithPopup@3x.png
Labels: skip dead code check

#4949 Add session id to `elements/session` call
  StripeCore/StripeCore/Source/Analytics/AnalyticsHelper.swift
  StripePaymentSheet/StripePaymentSheet/Source/Internal/API Bindings/STPAPIClient+PaymentSheet.swift
  StripePaymentSheet/StripePaymentSheetTests/PaymentSheet/STPAPIClient+PaymentSheetTest.swift
  StripePayments/StripePaymentsTestUtils/Resources/recorded_network_traffic/PaymentSheetAPITest/testUpdate/0000_get_v1_elements_sessions.tail
  StripePayments/StripePaymentsTestUtils/Resources/recorded_network_traffic/PaymentSheetAPITest/testUpdate/0001_get_v1_elements_sessions.tail
  StripePayments/StripePaymentsTestUtils/Resources/recorded_network_traffic/PaymentSheetAPITest/testUpdate/0002_get_v1_elements_sessions.tail
  StripePayments/StripePaymentsTestUtils/Resources/recorded_network_traffic/PaymentSheetAPITest/testUpdateFails/0000_get_v1_elements_sessions.tail
  StripePayments/StripePaymentsTestUtils/Resources/recorded_network_traffic/PaymentSheetAPITest/testUpdateFails/0001_get_v1_elements_sessions.tail
  StripePayments/StripePaymentsTestUtils/Resources/recorded_network_traffic/PaymentSheetAPITest/testUpdateFails/0002_get_v1_elements_sessions.tail
  StripePayments/StripePaymentsTestUtils/Resources/recorded_network_traffic/PaymentSheetAPITest/testUpdateIgnoresInFlightUpdate/0000_get_v1_elements_sessions.tail
  StripePayments/StripePaymentsTestUtils/Resources/recorded_network_traffic/PaymentSheetAPITest/testUpdateIgnoresInFlightUpdate/0001_get_v1_elements_sessions.tail
  StripePayments/StripePaymentsTestUtils/Resources/recorded_network_traffic/PaymentSheetAPITest/testUpdateIgnoresInFlightUpdate/0002_get_v1_elements_sessions.tail
  StripePayments/StripePaymentsTestUtils/STPNetworkStubbingTestCase.swift
Labels: skip dead code check

#4928 traitCollectionDidChange loading indicator
  StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/ViewControllers/LoadingViewController.swift
Labels: modifies public API
